_BASE_: "../Base-BoxSnake-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_swin_fpn_backbone"
  WEIGHTS: "./pretrained/swin_large_patch4_window12_384_22k.pkl"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: True
  ROI_MASK_HEAD:
    NAME: "PolygonHead"
    POOLER_TYPE: ""
  POLYGON_HEAD:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    PRED_WITHIN_BOX: False
    POLY_NUM_PTS: 64
    CLS_AGNOSTIC_MASK: True
    PREPOOL: False
    UPSAMPLING: False
  DIFFRAS:
    RESOLUTIONS: (64, 64, 64, 64, 64, 64, 64, 64)
    USE_RASTERIZED_GT: False
    INV_SMOOTHNESS_SCHED: (0.1,)
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    PROPOSAL_ONLY_GT: False
  BOX_SUP:
    ENABLE: True
    LOSS_POINTS_PROJ: True
    LOSS_POINTS_PROJ_WEIGHT: 1.0
    LOSS_LOCAL_PAIRWISE: True
    LOSS_PAIRWISE_WARMUP_ITER: 10000
    LOCAL_PAIRWISE_KERNEL_SIZE: 3
    LOCAL_PAIRWISE_DILATION: 2
    LOSS_LOCAL_PAIRWISE_WEIGHT: 0.5
    LOSS_GLOBAL_PAIRWISE: True
    LOSS_GLOBAL_PAIRWISE_WEIGHT: 0.03
    CROP_PREDICTS: True
    CROP_SIZE: 64
    MASK_PADDING_SIZE: 4
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_NORM: 0.0
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  CLIP_GRADIENTS:
    ENABLED: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
VIS_PERIOD: 0
TEST:
  EVAL_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800) # DETR aug
  FORMAT: "RGB" # for swin
